### ISSUE TITLE
Suggestion: Remove Air Hike height limit.

### ISSUE THREAD

**Issue by Monkeor** [muhopensores/dmc4_hook#36]
I often DT cancel at low height with Nero, but the game has a height limit to air hike, meaning I can't cancel DT activation if I'm too close to the ground.

**Comment by SSSiyan** [comment]
I added this as its own checkbox because I imagine a lot of people like to mash jump in panic to grab some iframes and airhike would deny you them
https://github.com/muhopensores/dmc4_hook/commit/cea8cea59f3292d5abc9059d695bdfed6552b0b4
[dinput8.zip](https://github.com/muhopensores/dmc4_hook/files/13851807/dinput8.zip)

**Comment by Monkeor** [comment]
This is fantastic and helps a ton for consistency, but I'm also noticing that DT cancelling Calibur with height restrictions off just above the ground can snap Nero to the floor, making it so that I can't air hike out of DT activation. Would it be possible to also make an option for jump to also cancel grounded DT activation?

**Comment by SSSiyan** [comment]
Added Grounded DT Cancel to Selective Cancels (at the bottom of the character page)
[dinput8.zip](https://github.com/muhopensores/dmc4_hook/files/13855619/dinput8.zip)
https://github.com/muhopensores/dmc4_hook/commit/d8a77220425ad8089f9c1596b1f9ede37870653c
